---
lr: 0.007876941994472506
weight_decay: 0
momentum: 0.9264232659838044
batch_size: 2
patch_size: 64
samples_per_volume: 128
max_length: 256
act: ReLU
seed: 42
train_val_ratio: 0.8
train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped/images/
train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped/labels/
test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped/test_images/
test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped/test_labels/
num_encoding_blocks: 4
out_channels_first_layer: 32
pooling_type: avg
upsampling_type: linear
dropout: 0
balanced_sampler: True
debug_plots: False
peak_min_distance: 5
peak_min_val: 0.4
...