---
lr: 0.007876941994472506
weight_decay: 0
momentum: 0.9264232659838044
batch_size: 2
patch_size: 64
samples_per_volume: 128
max_length: 256
act: ReLU
seed: 42
train_val_ratio: 0.8
train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped_with_csv_labs/images_10/
train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped_with_csv_labs/labels_10/
test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped_with_csv_labs/test_images_10/
test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/cropped_with_csv_labs/test_labels_10/
histogram_landmarks_path: ./fiddlercrab_landmarks_test.npy
num_encoding_blocks: 4
out_channels_first_layer: 32
pooling_type: avg
upsampling_type: linear
dropout: 0
balanced_sampler: True
debug_plots: False
peak_min_distance: 5
peak_min_val: 0.4
starting_sigma: 3
learn_sigma: False
ignore_empty_volumes: True
...