config:
  batch_size: 4
  channels: !!python/tuple
  - 64
  - 128
  - 256
  - 512
  lr: 1.0e-06
  max_length: 800
  momentum: 0.99
  patch_size: 64
  samples_per_volume: 40
  strides: !!python/tuple
  - 2
  - 2
  - 2
  weight_decay: 0.0005
