act: relu
batch_size: 4
config:
  act: relu
  batch_size: 4
  features: &id001 !!python/tuple
  - 64
  - 64
  - 128
  - 256
  - 512
  - 64
  features_scalar: 1
  lr: 4.1621394154757346e-08
  max_length: 400
  momentum: 0.9400655182801285
  patch_size: 32
  samples_per_volume: 80
  seed: 42
  test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
  test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
  train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
  train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
  train_val_ratio: 0.8
  weight_decay: 0.01
features: *id001
features_scalar: 1
lr: 4.1621394154757346e-08
max_length: 400
momentum: 0.9400655182801285
patch_size: 32
samples_per_volume: 80
seed: 42
test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
train_val_ratio: 0.8
weight_decay: 0.01
