config:
  act: relu
  batch_size: 2
  features: !!python/tuple
  - 64
  - 64
  - 128
  - 256
  - 512
  - 64
  lr: 0.01
  max_length: 400
  momentum: 0.99
  patch_size: 64
  samples_per_volume: 40
  weight_decay: 0.0
