# model params
seed: 44
lr: 0.0424937961824346
num_steps: 600000
weight_decay: 1.52709371682483e-06
momentum: 0.510999549987835
nesterov: False
act: ReLU
output_activation: None
softargmax: False
num_encoding_blocks: 5
out_channels_first_layer: 32
double_channels_with_depth: True
pooling_type: max
upsampling_type: conv
dropout: 0.0175756794552526
loss_in_sigma_space: False
debug_plots: False
mse_with_f1: False
visualise_model: False
learn_sigma: False
optimiser: SGD
pin_memory: False

# dataset params
train_images_dir: ./dataset/cystisoma_corneas/whole/train_images_10/
train_labels_dir: ./dataset/cystisoma_corneas/whole/train_labels_10/
test_images_dir: ./dataset/cystisoma_corneas/whole/train_images_10/
test_labels_dir: ./dataset/cystisoma_corneas/whole/train_labels_10/
image_suffix: image
label_suffix: corneas
train_val_ratio: 0.8
batch_size: 2
patch_size: 64
samples_per_volume: 128
max_length: 512 # max number of volumes to load from training and testing set at a time in the queue
# max_length: 1024
balanced_sampler: True # if false, then only sample from areas with labels
balanced_sampler_max_length: 9 # how many max pixels from labels should you sample from
ignore_empty_volumes: True
starting_sigma: 2.5 # 2.7530064583885
heatmap_max_length: 64
random_affine_prob: 0.5 
random_affine_scale_range: 0.15
random_affine_rotation_range: 180
random_affine_translation_range: 0
random_elastic_deformation_prob: 0.5
random_elastic_deformation_num_control_points: 7
random_elastic_deformation_max_displacement: 7.5
random_log_gamma: 0
histogram_standardisation: False # True
histogram_landmarks_path: ./landmarks_files/paraphronima_corneas_landmarks.npy
z_normalisation: True
num_workers: 6 

# inference params
peak_min_val: 0.6
correct_prediction_distance: 6
subpix_accuracy: False # slows down training too much
relative_heatmap_peak: False
