---
# model params
seed: 44
lr: 0.02727010928084 
weight_decay: 0
momentum: 0.912121752277315
act: ReLU
output_activation: None
num_encoding_blocks: 4
out_channels_first_layer: 64
pooling_type: avg
upsampling_type: linear
dropout: 0.1 # 0
debug_plots: False
visualise_model: False
learn_sigma: False

# dataset params
train_images_dir: ./dataset/fiddlercrab_rhabdoms/cropped/train_images_7/
train_labels_dir: ./dataset/fiddlercrab_rhabdoms/cropped/train_labels_7/
test_images_dir: ./dataset/fiddlercrab_rhabdoms/cropped/test_images_7/
test_labels_dir: ./dataset/fiddlercrab_rhabdoms/cropped/test_labels_7/
image_suffix: image
label_suffix: rhabdoms
train_val_ratio: 0.8
batch_size: 1
patch_size: 64
samples_per_volume: 32
max_length: 64
balanced_sampler: True
balanced_sampler_max_length: 9 # how many pixels from labels should you sample from
ignore_empty_volumes: True
starting_sigma: 3.54103417180517
heatmap_max_length: 50
random_affine_prob: 1 # 0.04002158711364645
random_affine_scale_range: 0.15
random_affine_rotation_range: 180
random_affine_translation_range: 0
random_elastic_deformation_prob: 0.455095880784793
random_elastic_deformation_num_control_points: 7
random_elastic_deformation_max_displacement: 7.5
histogram_standardisation: True
histogram_landmarks_path: ./landmarks_files/fiddlercrab_rhabdoms_landmarks.npy
z_normalisation: True
num_workers: Auto

# inference params
# ran hyperparameter tuning with these parameters,
# however, a correct_prediction_distance this low seems very difficult for the
# model to do (as labelling the rhabdoms higher or lower up is also completely
# fine).
# peak_min_distance: 1 
# peak_min_val: 0.4
# correct_prediction_distance: 3
# Should rerun with these parameters
peak_min_distance: 3
peak_min_val: 0.5
correct_prediction_distance: 5
...
