---
# model params
seed: 44
lr: 0.000001
weight_decay: 0.0005
momentum: 0.99
act: ReLU
output_activation: None
num_encoding_blocks: 5
out_channels_first_layer: 128
pooling_type: avg
upsampling_type: linear
dropout: 0.1 # 0
loss_in_sigma_space: True
debug_plots: False
visualise_model: True
learn_sigma: False

# dataset params
train_images_dir: ./dataset/fiddlercrab_corneas/cropped/train_images_10/
train_labels_dir: ./dataset/fiddlercrab_corneas/cropped/train_labels_10/
test_images_dir: ./dataset/fiddlercrab_corneas/cropped/test_images_10/
test_labels_dir: ./dataset/fiddlercrab_corneas/cropped/test_labels_10/
image_suffix: image
label_suffix: corneas
train_val_ratio: 0.8
batch_size: 2
patch_size: 64
samples_per_volume: 128
max_length: 256
balanced_sampler: True
balanced_sampler_max_length: 9 # how many pixels from labels should you sample from
ignore_empty_volumes: True
starting_sigma: 3.1506021688421963
heatmap_max_length: 50
random_affine_prob: 1 # 0.04002158711364645
random_affine_scale_range: 0.15
random_affine_rotation_range: 180
random_affine_translation_range: 0
random_elastic_deformation_prob: 1 # 0.03240664362804589
random_elastic_deformation_num_control_points: 7
random_elastic_deformation_max_displacement: 7.5
histogram_standardisation: False # True
histogram_landmarks_path: ./landmarks_files/fiddlercrab_corneas_landmarks.npy
z_normalisation: True
num_workers: Auto

# inference params
peak_min_distance: 3
peak_min_val: 0.5
correct_prediction_distance: 5
...
