---
# model params
seed: 44
lr: 0.06032258538418116
weight_decay: 0
momentum: 0.9597897798554147
act: ReLU
output_activation: None
num_encoding_blocks: 5
out_channels_first_layer: 32
pooling_type: avg
upsampling_type: linear
dropout: 0.1 # 0
debug_plots: True
visualise_model: False
learn_sigma: False

# dataset params
train_images_dir: ./dataset/paraphronima_corneas/cropped/train_images_30/
train_labels_dir: ./dataset/paraphronima_corneas/cropped/train_labels_30/
test_images_dir: ./dataset/paraphronima_corneas/cropped/test_images_30/
test_labels_dir: ./dataset/paraphronima_corneas/cropped/test_labels_30/
image_suffix: image
label_suffix: corneas
train_val_ratio: 0.8
batch_size: 2
patch_size: 64
samples_per_volume: 128
max_length: 256
balanced_sampler: True
balanced_sampler_max_length: 9 # how many pixels from labels should you sample from
ignore_empty_volumes: True
starting_sigma: 5
heatmap_max_length: 100
random_affine_prob: 1 # 0.04002158711364645
random_affine_scale_range: 0.15
random_affine_rotation_range: 180
random_affine_translation_range: 0
random_elastic_deformation_prob: 1 # 0.03240664362804589
random_elastic_deformation_num_control_points: 7
random_elastic_deformation_max_displacement: 7.5
histogram_standardisation: False # True
histogram_landmarks_path: ./landmarks_files/paraphronima_corneas_landmarks.npy
z_normalisation: True
num_workers: Auto

# inference params
peak_min_distance: 3
peak_min_val: 0.5
correct_prediction_distance: 5
...
