act: relu
batch_size: 2
config:
  act: relu
  batch_size: 2
  features: &id001 !!python/tuple
  - 64
  - 64
  - 128
  - 256
  - 512
  - 64
  features_scalar: 0.5
  lr: 0.0993827243937081
  max_length: 64
  momentum: 0.9216494800071414
  patch_size: 32
  samples_per_volume: 32
  seed: 42
  test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
  test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
  train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
  train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
  train_val_ratio: 0.8
  weight_decay: 1.0e-06
features: *id001
features_scalar: 0.5
lr: 0.0993827243937081
max_length: 64
momentum: 0.9216494800071414
patch_size: 32
samples_per_volume: 32
seed: 42
test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
train_val_ratio: 0.8
weight_decay: 1.0e-06
