act: relu
batch_size: 2
config:
  act: relu
  batch_size: 2
  features: &id001 !!python/tuple
  - 64
  - 64
  - 128
  - 256
  - 512
  - 64
  features_scalar: 1
  lr: 1.4072859783582895e-05
  max_length: 400
  momentum: 0.9719047334030768
  patch_size: 64
  samples_per_volume: 40
  seed: 42
  test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
  test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
  train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
  train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
  train_val_ratio: 0.8
  weight_decay: 0.0001
features: *id001
features_scalar: 1
lr: 1.4072859783582895e-05
max_length: 400
momentum: 0.9719047334030768
patch_size: 64
samples_per_volume: 40
seed: 42
test_images_dir: /home/jake/projects/mctnet/dataset/fiddler/test_images/
test_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/test_labels/
train_images_dir: /home/jake/projects/mctnet/dataset/fiddler/images/
train_labels_dir: /home/jake/projects/mctnet/dataset/fiddler/labels/
train_val_ratio: 0.8
weight_decay: 0.0001
